/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textplayer;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author leonardo.rosa
 */
public class HelpForm extends javax.swing.JFrame {

    public static final int ENABLED = 0x01;
    public static final int DISABLED = 0x02;
    
    private int status;
    
    
    public HelpForm() {
        initComponents();
    }
    
    public int getStatus()
    {
        return status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setTitle("Help Me");
        setResizable(false);

        String displayText = displayHelpText();
        if (displayText != null)
		{
			jLabel1.setText(displayHelpText());
			status = ENABLED;
        

			javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
			getContentPane().setLayout(layout);
			layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(8, 8, 8)
					.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
					.addGap(8, 8, 8))
			);
			layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addGap(15, 15, 15)
					.addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
					.addGap(15, 15, 15))
				);

			pack();
		}
		
		else
		{
			JOptionPane.showMessageDialog(null,
				"Help function disabled.",
				"Error",
				JOptionPane.ERROR_MESSAGE);
			status = DISABLED;
		}
    }// </editor-fold>//GEN-END:initComponents
    
    private String displayHelpText()
    {
        List<String> readme = FileManager.loadFileByName("help.txt");
        
        if (readme != null) 
        {
            String displayed =  "<html>";
            for (String s : readme)
            {
                displayed += s;
                displayed += "<br>";
            }
            displayed += "</html>";
            
            return displayed;
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
