/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textplayer;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
/**
 *
 * @author Günter Hertz
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    List<String> instruments;
    Player player;
    
    private final static int bpmChangeAmount = SoundTrack.BPM_CHANGE_AMOUNT;
    private final static int defaultBPM = 120;
    private final static int maxBpm = SoundTrack.MAX_BPM;
    private final static int minBpm = SoundTrack.MIN_BPM;
    
    private final HelpForm helpForm;
    
    public MainFrame() throws MidiUnavailableException {
        instruments = InstrumentList.get();
        initComponents();
        player = new Player();
        helpForm = new HelpForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        addInstrumentButton = new java.awt.Button();
        addAllInstrumentsButton = new java.awt.Button();
        removeAllInstrumentsButton = new java.awt.Button();
        removeInstrumentButton = new java.awt.Button();
        textAreaLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        availableInstruments = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        usedInstruments = new javax.swing.JList<>();
        availableInstrumentsLabel = new javax.swing.JLabel();
        usedInstrumentsLabel = new javax.swing.JLabel();
        bpmTitleLabel = new javax.swing.JLabel();
        bpmLabel = new javax.swing.JLabel();
        increaseBPM = new java.awt.Button();
        lowerBPM = new java.awt.Button();
        menuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        loadFileMenu = new javax.swing.JMenuItem();
        saveTxtMenu = new javax.swing.JMenuItem();
        saveMidiMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        helpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TextPlayer");
        setResizable(false);
        setSize(new java.awt.Dimension(748, 600));

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);
        textArea.setLineWrap(true);

        textArea.setWrapStyleWord(true);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/playicon.png"))); // NOI18N
        playButton.setPreferredSize(new java.awt.Dimension(120, 30));
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        stopButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/stopicon.png"))); // NOI18N
        stopButton.setPreferredSize(new java.awt.Dimension(120, 30));
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        addInstrumentButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        addInstrumentButton.setLabel(">");
        addInstrumentButton.setPreferredSize(new java.awt.Dimension(100, 30));
        addInstrumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInstrumentButtonActionPerformed(evt);
            }
        });

        addAllInstrumentsButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        addAllInstrumentsButton.setLabel(">>");
        addAllInstrumentsButton.setPreferredSize(new java.awt.Dimension(100, 30));
        addAllInstrumentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAllInstrumentsButtonActionPerformed(evt);
            }
        });

        removeAllInstrumentsButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        removeAllInstrumentsButton.setLabel("<<");
        removeAllInstrumentsButton.setPreferredSize(new java.awt.Dimension(100, 30));
        removeAllInstrumentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllInstrumentsButtonActionPerformed(evt);
            }
        });

        removeInstrumentButton.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        removeInstrumentButton.setLabel("<");
        removeInstrumentButton.setPreferredSize(new java.awt.Dimension(100, 30));
        removeInstrumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeInstrumentButtonActionPerformed(evt);
            }
        });

        textAreaLabel.setText("Text to be played:");

        jScrollPane2.setViewportView(availableInstruments);
        DefaultListModel availableModel = new DefaultListModel();
        for (String s : instruments)
        availableModel.addElement(s);
        availableInstruments.setModel(availableModel);

        jScrollPane3.setViewportView(usedInstruments);
        DefaultListModel usedModel = new DefaultListModel();
        usedInstruments.setModel(usedModel);

        availableInstrumentsLabel.setText("Available Instruments");

        usedInstrumentsLabel.setText("Used Instruments");

        bpmTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpmTitleLabel.setText("BPM");

        bpmLabel.setBackground(new java.awt.Color(255, 255, 255));
        bpmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpmLabel.setText("120");

        increaseBPM.setActionCommand("+");
        increaseBPM.setLabel("+");
        increaseBPM.setName(""); // NOI18N
        increaseBPM.setPreferredSize(new java.awt.Dimension(35, 35));
        increaseBPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseBPMActionPerformed(evt);
            }
        });

        lowerBPM.setLabel("-");
        lowerBPM.setPreferredSize(new java.awt.Dimension(35, 35));
        lowerBPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerBPMActionPerformed(evt);
            }
        });

        FileMenu.setText("File");

        loadFileMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        loadFileMenu.setText("Load File");
        loadFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuActionPerformed(evt);
            }
        });
        FileMenu.add(loadFileMenu);

        saveTxtMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveTxtMenu.setText("Save File");
        saveTxtMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTxtMenuActionPerformed(evt);
            }
        });
        FileMenu.add(saveTxtMenu);

        saveMidiMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        saveMidiMenu.setText("Save MIDI");
        saveMidiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMidiMenuActionPerformed(evt);
            }
        });
        FileMenu.add(saveMidiMenu);

        menuBar.add(FileMenu);

        HelpMenu.setText("Help");

        helpMenu.setText("Read Me");
        helpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpMenuActionPerformed(evt);
            }
        });
        HelpMenu.add(helpMenu);

        menuBar.add(HelpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textAreaLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bpmTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                        .addComponent(bpmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(increaseBPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lowerBPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeAllInstrumentsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeInstrumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addAllInstrumentsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addInstrumentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(availableInstrumentsLabel))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usedInstrumentsLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textAreaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(addAllInstrumentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(removeAllInstrumentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(removeInstrumentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(stopButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availableInstrumentsLabel)
                            .addComponent(usedInstrumentsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bpmTitleLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bpmLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(increaseBPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowerBPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpMenuActionPerformed
        helpForm.setVisible(true);
    }//GEN-LAST:event_helpMenuActionPerformed

    private void loadFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuActionPerformed
        List<String> loadedText;
        loadedText = FileManager.loadFromFile();
        if (loadedText != null)
            displayText(loadedText);
    }//GEN-LAST:event_loadFileMenuActionPerformed

    private void saveTxtMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTxtMenuActionPerformed
        String displayedText = textArea.getText();
        FileManager.saveToFile(displayedText);
    }//GEN-LAST:event_saveTxtMenuActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        
        int playerStatus = player.getStatus();
        
        if (playerStatus == Player.STOPPED || playerStatus == Player.NOT_INITIALIZED)
        {
            if (getInstrumentsList().size() > 0)
            {
                try 
                {
                    textArea.setEditable(false);
                    playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/pauseicon.png")));

                    setPlayer();
                    runPlayer();
                }
                //If player is paused, then resume
                catch (NumberFormatException | MidiUnavailableException | InvalidMidiDataException ex) 
                {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Choose at least one instrument.", "Error", ERROR_MESSAGE);
        }
        
        else if (playerStatus == Player.PAUSED)
        {
            playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/pauseicon.png")));
            resumePlayer();
        }
        
        //If player is playing, then pause
        else if (playerStatus == Player.PLAYING) 
        {
            playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/playicon.png")));
            pausePlayer();
        }
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
        
        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textplayer/playicon.png")));
        textArea.setEditable(true);
        updateBPMLabel(defaultBPM);
        stopPlayer();
           
    }//GEN-LAST:event_StopButtonActionPerformed

    private void pausePlayer() {
        player.pause();
    }

    private void resumePlayer() {
        player.resume();
    }

    private void setPlayer() throws NumberFormatException, MidiUnavailableException, InvalidMidiDataException {
        
        List<String> instruments = getInstrumentsList();
        String song = textArea.getText();
        int bpm = getBpmAsInt();
        Sequencer sequencer = MidiSystem.getSequencer();
        Sequence sequence = createSequence(instruments, song, bpm);
        
        sequencer.addMetaEventListener((MetaMessage msg) -> {
            stopButtonActionPerformed(null);
        });
        player.setSequence(sequence);
        player.setSequencer(sequencer);
    }

    private void runPlayer() {
        try {
            player.play();
        } catch (InterruptedException | MidiUnavailableException | InvalidMidiDataException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void stopPlayer() {
        player.stop();
    }

    private Sequence createSequence(List<String> instruments1, String song, int bpm) throws MidiUnavailableException {
        Sequence sequence = null;
        List<Instrument> inst = InstrumentList.stringToInstrument(instruments1);
        try {
            sequence = SoundSequence.createSoundSequence(inst, song, bpm);
        }catch (InvalidMidiDataException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return sequence;
    }

    private int getBpmAsInt() throws NumberFormatException {
        //Get bpm from GUI
        String bpmString = bpmLabel.getText();
        int bpm = Integer.parseInt(bpmString);
        return bpm;
    }

    private List<String> getInstrumentsList() {
        //Get list of instruments from GUI
        DefaultListModel used = (DefaultListModel) usedInstruments.getModel();
        List<String> instruments = ListModelManipulation.toString(used);
        return instruments;
    }
    
    private void addInstrumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInstrumentButtonActionPerformed

        DefaultListModel available = (DefaultListModel) availableInstruments.getModel();
        DefaultListModel used = (DefaultListModel) usedInstruments.getModel();       

        String selectedInstrument = availableInstruments.getSelectedValue(); 
        List<DefaultListModel> updatedModels;
        updatedModels = ListModelManipulation.moveElement(available, used, selectedInstrument);
        
        availableInstruments.setModel(updatedModels.get(0));
        usedInstruments.setModel(updatedModels.get(1));
        
    }//GEN-LAST:event_addInstrumentButtonActionPerformed

    private void addAllInstrumentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllInstrumentsButtonActionPerformed
        
        DefaultListModel available = (DefaultListModel) availableInstruments.getModel();
        DefaultListModel used = (DefaultListModel) usedInstruments.getModel();
        
        List<DefaultListModel> updatedModels;
        updatedModels = ListModelManipulation.moveAllElements(available, used);
        
        availableInstruments.setModel(updatedModels.get(0));
        usedInstruments.setModel(updatedModels.get(1));
        
    }//GEN-LAST:event_addAllInstrumentsButtonActionPerformed

    private void removeAllInstrumentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAllInstrumentsButtonActionPerformed
        
        DefaultListModel available = (DefaultListModel) availableInstruments.getModel();
        DefaultListModel used = (DefaultListModel) usedInstruments.getModel();
        
        List<DefaultListModel> updatedModels;
        updatedModels = ListModelManipulation.moveAllElements(used, available);
        
        availableInstruments.setModel(updatedModels.get(1));
        usedInstruments.setModel(updatedModels.get(0));
    }//GEN-LAST:event_removeAllInstrumentsButtonActionPerformed

    private void removeInstrumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeInstrumentButtonActionPerformed
        DefaultListModel available = (DefaultListModel) availableInstruments.getModel();
        DefaultListModel used = (DefaultListModel) usedInstruments.getModel();
        
        String selectedInstrument = usedInstruments.getSelectedValue(); 
        List<DefaultListModel> updatedModels;
        updatedModels = ListModelManipulation.moveElement(used, available, selectedInstrument);
        
        availableInstruments.setModel(updatedModels.get(1));
        usedInstruments.setModel(updatedModels.get(0));
    }//GEN-LAST:event_removeInstrumentButtonActionPerformed

    private void increaseBPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseBPMActionPerformed
        
        int bpmInteger = getBpmAsInt();
        bpmInteger += bpmChangeAmount;
        
        if (bpmInteger <= maxBpm)
        {
            updateBPMLabel(bpmInteger);

            if (player.getStatus() != Player.NOT_INITIALIZED)
                player.increaseBPM(bpmChangeAmount);
        }

    }//GEN-LAST:event_increaseBPMActionPerformed

    private void lowerBPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerBPMActionPerformed
        
        int bpmInteger = getBpmAsInt();
        bpmInteger -= bpmChangeAmount;
        
        if (bpmInteger >= minBpm)
        {
            updateBPMLabel(bpmInteger);

            if (player.getStatus() != Player.NOT_INITIALIZED)
                player.decreaseBPM(bpmChangeAmount);
        }
    }//GEN-LAST:event_lowerBPMActionPerformed

    private void saveMidiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMidiMenuActionPerformed
        
        List<String> instruments = getInstrumentsList();
        String song = textArea.getText();
        int bpm = getBpmAsInt();
        try 
        {
            Sequence sequence = createSequence(instruments, song, bpm);
            MidiManager.saveMidi(sequence);
        } 
        catch (MidiUnavailableException ex) 
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveMidiMenuActionPerformed

    private void updateBPMLabel(int bpmInteger) {
        bpmLabel.setText(Integer.toString(bpmInteger));
    }

    //Sets the text on jTextArea1
    private void displayText(List<String> text)
    {
        if (!text.isEmpty())
        {
            int i;
            textArea.setText(null); //clear the existing text
            for (i = 0; i < text.size()-1; i++)
            {
                textArea.append(text.get(i) + "\n");
            }
            textArea.append(text.get(i));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private java.awt.Button addAllInstrumentsButton;
    private java.awt.Button addInstrumentButton;
    private javax.swing.JList<String> availableInstruments;
    private javax.swing.JLabel availableInstrumentsLabel;
    private javax.swing.JLabel bpmLabel;
    private javax.swing.JLabel bpmTitleLabel;
    private javax.swing.JMenuItem helpMenu;
    private java.awt.Button increaseBPM;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenuItem loadFileMenu;
    private java.awt.Button lowerBPM;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton playButton;
    private java.awt.Button removeAllInstrumentsButton;
    private java.awt.Button removeInstrumentButton;
    private javax.swing.JMenuItem saveMidiMenu;
    private javax.swing.JMenuItem saveTxtMenu;
    private javax.swing.JButton stopButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel textAreaLabel;
    private javax.swing.JList<String> usedInstruments;
    private javax.swing.JLabel usedInstrumentsLabel;
    // End of variables declaration//GEN-END:variables
}
